### PR TITLE
Scripted examples

### PR DESCRIPTION
**Pull request by james-trayford**
- Modify included examples in "*.py" format, alongside `*.ipynb` examples - tihs is intended for those using screen-readers while _Jupyter_ is inaccessible
- Add the `hear()` method to the `Sonification` class, this plays directly to the soundcard so can play in the command-line.
- Add requirement for the `sounddevice` module to allow this access to soundcard - therefore requires reinstall or to `pip install sounddevice` inside `strauss` environment
- Added these as pre-merge tests, and update GitHub protocols to  check for `*.py` files in tests

### CODE REVIEW

**Comment by SamYoules** [comment]
Needed to install libportaudio2. Added absolute pathnames. The new .py scripts work on my system.

**Review by SamYoules — COMMENTED** [review]
Needed to install libportaudio2. Added absolute pathnames. The new .py scripts work on my system.

**Comment by james-trayford** [comment]
Is there anything else needed before merging this?

**Comment by SamYoules** [comment]
No, I don't think so.

**Review by SamYoules — APPROVED** [review]

**Pull request merged**
